server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/weather?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update

weatherApi:
  url: https://api.openweathermap.org
  appid: ebd6f86c615c06d3606d3579f5dba716
  units: metric
  endpoints:
    currentWeather: /data/2.5/weather

cadence:
  domain: testDomainName
  task-list: testTaskList
